{{- range $k, $v := .Values.modeloCarga }}
{{- range $c := $v.channels }}
---   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cameras.fullname" $ }}-carga-{{$k}}-ch{{$c}}
  namespace: {{ $.Values.env }}
  labels:
    {{- include "cameras.labels" $ | nindent 4 }}-carga-{{$k}}-ch{{$c}}
spec:
  selector:
    matchLabels:
      {{- include "cameras.selectorLabels" $ | nindent 6 }}-carga-{{$k}}-ch{{$c}}
  replicas: 1
  template:     
    metadata:  
      labels:
        {{- include "cameras.selectorLabels" $ | nindent 8 }}-carga-{{$k}}-ch{{$c}}
    spec:   
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"   
        {{- if $v.gpu }}
        cloud.google.com/gke-accelerator: {{ $v.accelarator }}
        {{- end }}     
      serviceAccountName: {{ $.Values.serviceAccount.name }}
      containers:
        - name: modelo-carga
          image: "{{ $.Values.images.containerImage.repository }}:{{ $.Values.images.containerImage.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.images.containerImage.pullPolicy }}
          command: ["python3", "charge_model.py"]
          env:
            {{- if $v.secrets }}
            - name: RTSP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $v.secrets }}
                  key: user
            - name: RTSP_PWD
              valueFrom:
                secretKeyRef:
                  name: {{ $v.secrets }}
                  key: password
            {{- end }}
            {{- if $v.conf }}
            - name: TRACK_CONF
              value: "{{ $v.conf }}"
            {{- end }}
            {{- if $v.iou }}
            - name: TRACK_IOU
              value: "{{ $v.iou }}"   
            {{- end }}
            - name: RTSP_ENDPOINT
              value: {{ printf "%v?channel=%v&subtype=%v" $v.rtsp $c $v.subtype }}       
            - name: POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name   
            - name: PUBSUB_TOPIC
              value: {{ $v.pubsub }}
            - name: GCP_PROJECT
              value: {{ $.Values.gcpProject }}     
            - name: SPOT
              value: "{{ $k }}"
            - name: CHANNEL
              value: "{{ $c }}" 
          {{- if $v.gpu }} 
          resources:
            limits:
              nvidia.com/gpu: 1     
          {{- end }}
          volumeMounts:
            - name: vol-carga-{{$k}}-ch{{$c}}-data
              mountPath: /app/output
              readOnly: false    

        - name: modelo-experto
          image: "{{ $.Values.images.containerImage.repository }}:{{ $.Values.images.containerImage.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.images.containerImage.pullPolicy }}
          command: ["python3", "expert_model.py"]
          env:
            {{- if $v.secrets }}
            - name: RTSP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $v.secrets }}
                  key: user
            - name: RTSP_PWD
              valueFrom:
                secretKeyRef:
                  name: {{ $v.secrets }}
                  key: password
            {{- end }}
            {{- if $v.conf }}
            - name: TRACK_CONF
              value: "{{ $v.conf }}"
            {{- end }}
            {{- if $v.iou }}
            - name: TRACK_IOU
              value: "{{ $v.iou }}"   
            {{- end }}
            - name: RTSP_ENDPOINT
              value: {{ printf "%v?channel=%v&subtype=%v" $v.rtsp $c $v.subtype }}       
            - name: POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name   
            - name: PUBSUB_TOPIC
              value: {{ $v.pubsub }}
            - name: GCP_PROJECT
              value: {{ $.Values.gcpProject }}     
            - name: SPOT
              value: "{{ $k }}"
            - name: CHANNEL
              value: "{{ $c }}" 
          {{- if $v.gpu }} 
          resources:
            limits:
              nvidia.com/gpu: 1     
          {{- end }}
          volumeMounts:
            - name: vol-carga-{{$k}}-ch{{$c}}-data
              mountPath: /app/output
              readOnly: false

        - name: cleanner
          image: "ubuntu:24.04"
          imagePullPolicy: {{ $.Values.images.containerImage.pullPolicy }}
          command: ["/bin/sh", "-c"]

          args: 
          - |
            while true
            do
            echo ----------------------------------------
            echo deleting files:
            find /app/output -name *.webm -type f -mmin +${MAX_TIME_MINUTES}
            find /app/output -name *.webm -type f -mmin +${MAX_TIME_MINUTES} -delete
            sleep 60
            echo ----------------------------------------
            done
          env:  
            - name: MAX_TIME_MINUTES
              value: "90"
          volumeMounts:
            - name: vol-carga-{{$k}}-ch{{$c}}-data
              mountPath: /app/output
              readOnly: false

        - name: web
          image: "{{ $.Values.images.containerImage.repository }}:{{ $.Values.images.containerImage.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.images.containerImage.pullPolicy }}
          command: ["python3", "app.py"]
          env:  
            - name: SPOT
              value: "{{ $k }}"
            - name: CHANNEL
              value: "{{ $c }}"      
            - name: ENABLE_AUTH
              value: "true"     
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: vol-carga-{{$k}}-ch{{$c}}-data
              mountPath: /app/output
              readOnly: false 
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080                     
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080          
      volumes:
        - name: vol-carga-{{$k}}-ch{{$c}}-data
          emptyDir:
            sizeLimit: 100Gi        
{{- end }}
{{- end }}