apiVersion: v1
kind: Secret
metadata:
  name: rtsp-secret
  namespace: {{ .Values.env }}
data:
  user: cHJveWVjdG8=
  password: cHJveWVjdG8yMDI0
---
apiVersion: v1
kind: Secret
metadata:
  name: clousql-secret
  namespace: {{ .Values.env }}
data:
  user: YXBwLXVzZXI=
  password: MWYxdHl4QD1rdWdeRiVTdA==
  instance: cmFpemVuLXNtLXNxbA==