replicaCount: 1
env: poc
gcpProject: raizen-genai-01

images:
  containerImage:
    repository: us-central1-docker.pkg.dev/raizen-genai-01/raizen-sm-artifact/raizen-sm-app
    pullPolicy: IfNotPresent
    tag: v1.0.11

# imagePullSecret:
#   name: dockerhub-credentials

serviceAccount:
  create: true
  name: computer-vision-app

modeloCarga:
  1506:
    gpu: true
    ingress: true
    iou: "0.6"
    conf: "0.4"    
    accelarator: nvidia-l4
    pubsub: "vision_app"
    rtsp: "11.37.69.100/cam/realmonitor"
    secrets: rtsp-secret
    subtype: 1
    channels:
    - 25

modeloConteo:
  1506:
    gpu: true
    ingress: true
    iou: "0.6"
    conf: "0.4"
    accelarator: nvidia-l4
    pubsub: "vision_app"
    rtsp: "11.37.69.100/cam/realmonitor"
    secrets: rtsp-secret
    subtype: 1
    channels:
    - 1
    - 2 
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9