# WARNING: this roles are too permissive, only use for POC environment
# helm upgrade --install sm-poc .
#
# To bind the service account to the workload identity pool, run the following command:
# gcloud projects add-iam-policy-binding projects/raizen-genai-01 \
#     --role=roles/pubsub.admin \
#     --member=principal://iam.googleapis.com/projects/980463466363/locations/global/workloadIdentityPools/raizen-genai-01.svc.id.goog/subject/ns/poc/sa/computer-vision-app \
#     --condition=None

# gcloud projects add-iam-policy-binding projects/raizen-genai-01 \
#     --role=roles/storage.objectAdmin \
#     --member=principal://iam.googleapis.com/projects/980463466363/locations/global/workloadIdentityPools/raizen-genai-01.svc.id.goog/subject/ns/poc/sa/computer-vision-app \
#     --condition=None

# gcloud projects add-iam-policy-binding projects/raizen-genai-01 \
#     --role=roles/cloudsql.client \
#     --member=principal://iam.googleapis.com/projects/980463466363/locations/global/workloadIdentityPools/raizen-genai-01.svc.id.goog/subject/ns/poc/sa/computer-vision-app \
#     --condition=None
replicaCount: 1
env: poc
gcpProject: raizen-genai-01

images:
  containerImage:
    repository: us-central1-docker.pkg.dev/raizen-genai-01/raizen-sm-artifact/raizen-sm-app
    pullPolicy: IfNotPresent
    tag: v2.0.4

# imagePullSecret:
#   name: dockerhub-credentials
secrets:
  cloudsql: clousql-secret

serviceAccount:
  create: true
  name: computer-vision-app


modeloCarga:
  1506:
    gpu: true
    ingress: true
    iou: "0.4"
    conf: "0.6"    
    accelarator: nvidia-l4
    pubsub: "vision_app"
    rtsp: "11.37.69.100/cam/realmonitor"
    secrets: rtsp-secret
    subtype: 1
    gcsbucket: "raizen-training-data"
    channels:
    - 25

modeloConteo:
  1506:
    gpu: true
    ingress: true
    iou: "0.6"
    conf: "0.4"
    accelarator: nvidia-l4
    pubsub: "vision_app"
    rtsp: "11.37.69.100/cam/realmonitor"
    secrets: rtsp-secret
    subtype: 1
    channels:
    - 2 
    - 5
    - 6
    - 9

  1716:
    gpu: true
    ingress: true
    iou: "0.6"
    conf: "0.4"
    accelarator: nvidia-l4
    pubsub: "vision_app"
    rtsp: "11.45.69.100/cam/realmonitor"
    secrets: rtsp-secret
    subtype: 1
    channels:
    - 1
    - 2 
  #  - 3
  #  - 4

  1438:
    gpu: true
    ingress: true
    iou: "0.6"
    conf: "0.4"
    accelarator: nvidia-l4
    pubsub: "vision_app"
    rtsp: "11.32.69.100/cam/realmonitor"
    secrets: rtsp-secret
    subtype: 1
    channels:
    - 1
    - 2 
    # - 3
  
  1439:
    gpu: true
    ingress: true
    iou: "0.6"
    conf: "0.4"
    accelarator: nvidia-l4
    pubsub: "vision_app"
    rtsp: "11.31.69.100/cam/realmonitor"
    secrets: rtsp-secret
    subtype: 1
    channels:
    - 1
    - 2 
    # - 3

  1482:
    gpu: true
    ingress: true
    iou: "0.6"
    conf: "0.4"
    accelarator: nvidia-l4
    pubsub: "vision_app"
    rtsp: "11.36.69.100/cam/realmonitor"
    secrets: rtsp-secret
    subtype: 1
    channels:
    - 1
    - 2 
    # - 3
